### ISSUE TITLE
Draw nodes using Graphviz

### ISSUE THREAD

**Issue by OmarShawky1** [QAMichaelPeng/obsidian-graphviz#1]
I think this drawing method can be an alternative for the current graphing method that does not have any hierarchy in the relations and cannot be organized in a useful way, they just look nice but cannot be grasped in very populated notes

**Comment by QAMichaelPeng** [comment]
@OmarShawky1 I didn't get your point. Currently obsidian support mermaid without any plugin which have a bunch of great features, see
https://mermaid-js.github.io/mermaid/#/.
This plugin is just to fit some needs that can't be met easily by mermaid.

**Comment by OmarShawky1** [comment]
Just realized that :D, you do not know how much work i needed to do every time i needed to draw using graphviz.
