### ISSUE TITLE
Obsidian detects v1.0.4 but fails to install it

### ISSUE THREAD

**Issue by AntoineChn** [QAMichaelPeng/obsidian-graphviz#12]
As shown in the screenshot below, obsidian detects this new version of 1.0.4 but fails to install it.

*N.B.* this version 1.0.4 cannot be found in `Releases` : https://github.com/QAMichaelPeng/obsidian-graphviz/releases

![Screenshot 2022-08-20 at 23 29 37](https://user-images.githubusercontent.com/17791254/185766541-36db2001-d6f9-4576-9dc5-30c3351c3cf8.png)

**Comment by d0ssant0s** [comment]
Hi, unfortunately it is still failing to install. Console error:
```javascript
app.js:1 Error: net::ERR_SSL_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
```

**Comment by QAMichaelPeng** [comment]
My bad, I forgot to create a release for 1.0.4. Fixed. Please try again.
