### ISSUE TITLE
Version 1.0.4 fails to update or install on Obsidian 0.15.9

### ISSUE THREAD

**Issue by maccident** [QAMichaelPeng/obsidian-graphviz#14]
After being notified of an update, I attempted to update via the Community Plugin panel, and the update failed.

I uninstalled the plugin and attempted to install it, and the install failed.
<img width="549" alt="Screen Shot 2022-08-30 at 9 20 09 AM" src="https://user-images.githubusercontent.com/1326829/187489057-3e6b5a71-088e-4b6d-b33c-9c8e3fa4ecf3.png">

**Comment by ngirard** [comment]
I'm affected as well.

**Comment by PurpleGuitar** [comment]
I'm unable to update or install as well.  It looks like it's trying to download 1.0.4, but only 1.0.3 is available on the releases page.  Perhaps the manifest file got accidentally updated on the main branch?  

https://github.com/QAMichaelPeng/obsidian-graphviz/blob/main/manifest.json

**Comment by QAMichaelPeng** [comment]
Fixed, please try again. Sorry for the inconvenience.

**Comment by QAMichaelPeng** [comment]
@maccident @ngirard @PurpleGuitar

**Comment by ngirard** [comment]
Great, thanks @QAMichaelPeng !

**Comment by maccident** [comment]
Thanks!  It installed!
