### ISSUE TITLE
Where is the dot file?

### ISSUE THREAD

**Issue by scriptor-dga** [QAMichaelPeng/obsidian-graphviz#2]
I installed the plugin in Obsidian and Graphviz on Windows 10 but I have no clue where to find the DOT file.

**Comment by QAMichaelPeng** [comment]
It's under below directory under my Win 10.

`C:\Program Files\Graphviz\bin`

**Comment by scriptor-dga** [comment]
> It's under below directory under my Win 10.
> 
> `C:\Program Files\Graphviz\bin`

I get this error from the codeblock: `"C:\Program Files\Graphviz\bin -Tpng,C:\Users\dga\AppData\Local\Temp\tmp-19612-MefSc0JsUdfh" failed, Error: spawn C:\Program Files\Graphviz\bin ENOENT`

**Comment by QAMichaelPeng** [comment]
@scriptor-dga 
1. Please check if your dot is under same file
2. You should use the full path of the dot executable file, not the directory it's in, e.g. "C:\Program Files\Graphviz\bin\dot"
