### ISSUE TITLE
Encoding with utf-8

### ISSUE THREAD

**Issue by chumicat** [QAMichaelPeng/obsidian-graphviz#3]
## Problems: 
When the plugin render the dot code into graph, it cannot show non-ascii characters correctly.
![](https://i.imgur.com/2miVOWQ.png)

## Analysis: 
I had get some error message by give wrong dot path and know that the plugin use `-Tpng` as render parameter, and according to [this discussion](https://stackoverflow.com/questions/6743382/graphviz-not-supporting-utf-8-encoding), it might be a problem to show non-ascii charaters when convert to png format. .

## Conclusion: 
So I wondering, maybe offering a conversion type choice might be a good ide, or there might have some solution nowaday to render non-ascii characters correctly.

**Comment by QAMichaelPeng** [comment]
@chumicat , could you provide an example? I tried Chinese characters and they can be rendered correctly with the -Tpng option. 
And would you please let me know your operation system, and if you're using windows, the code page of it. 
Thanks.

**Comment by chumicat** [comment]
OS: Windows 10 HOME, Windows 10 Professional
Code: are as follow:
```dot
digraph G{
    subgraph cluster_SMS{
        C->D3->E3
        color=deeppink;
        label="SMS";
    }
    subgraph cluster_FW1{
        FW1->D1 [style=invis]
        D1->E1
        color=orange;
        label="FW1";
    }
    subgraph cluster_FW2{
        FW2->D2 [style=invis]
        D2->E2
        color=orange;
        label="FW2";
    }
    subgraph cluster_Win10{
        A->Z
        B

        color=blue;
        label="Win10";
    }
    
    A->D1
    A->D2
    A->D3
    B->D1
    B->D2
    B->D3

    A, B, C, D1, D2, D3, E1, E2, E3[shape=box]
    FW1, FW2 [style=invis]
    A [label="下載檔案 (A)"]
    B [label="安裝\nOpenSSH (B)"]
    C [label="清除 SMS\n未存變更 (C)"]
    A, B, C []
    D1, D2, D3 [label="上傳檔案 (D)"]
}
```

**Comment by QAMichaelPeng** [comment]
@chumicat 
It's a known issue of graphviz: 
https://gitlab.com/graphviz/graphviz/-/issues/1612
From the comments in the issue, changing format won't work
> @steveroush
> **But**, I tried the same thing on a **Windows** system (dot version 2.41.20191017.1352) and did NOT get a good result (svg was wrong and gif, png, and jpg were invalid - according to firefox).  
**dot** under **cygwin** gave a correct result. Hmmm.

There's a  work around on windows:
Set fontname to "Microsoft Yahei"


``` dot
digraph G{
  fontname = "Microsoft YaHei";

  fontsize = 12;
  node [ fontname = "Microsoft YaHei", fontsize = 12, shape = "record" ];
  edge [ fontname = "Microsoft YaHei", fontsize = 12 ];
   
  subgraph cluster_SMS{
        C->D3->E3
        color=deeppink;
        label="SMS";
    }
    subgraph cluster_FW1{
        FW1->D1 [style=invis]
        D1->E1
        color=orange;
        label="FW1";
    }
    subgraph cluster_FW2{
        FW2->D2 [style=invis]
        D2->E2
        color=orange;
        label="FW2";
    }
    subgraph cluster_Win10{
        A->Z
        B

        color=blue;
        label="Win10";
    }
    
    A->D1
    A->D2
    A->D3
    B->D1
    B->D2
    B->D3

    A, B, C, D1, D2, D3, E1, E2, E3[shape=box]
    FW1, FW2 [style=invis]
    A [label="下載檔案 (A)"]
    B [label="安裝\nOpenSSH (B)"]
    C [label="清除 SMS\n未存變更 (C)"]
    A, B, C []
    D1, D2, D3 [label="上傳檔案 (D)"]
}
```
Reference: [Graphviz(02) 汉字subgraph不显示汉字的处理](http://www.manongjc.com/detail/6-viduwccrknmazok.html)

**Comment by chumicat** [comment]
Thanks for the solution!
